### ISSUE TITLE
Consulta com vários valores de um mesmo campo e operadores diferentes

### ISSUE THREAD

**Issue by albertoavila** [investira/investira.server.sdk.js#4]
Não é possível fazer uma consulta com vários valores e operadores diferentes para um mesmo campo. Por ex: WHERE data >= '2019-06-01' AND data <= '2019-06-18'

**Comment by rvillar** [comment]
Não seria simplesmente criar uma view com o campo “data” incluído duas vezes no select com nomes diferentes? Ex: data as data_inicio, data as data_fim.

**Comment by albertoavila** [comment]
Foram criados os campos DATA_INICIO e DATA_FIM às views que necessitam desta funcionalidade.
